### PR TITLE
666 enhancement validate new user email against existing previous emails

### PR DESCRIPTION
**Pull request by shrprabh**
- Separated checks for duplicate email in the email field and previousEmails array.
- Improved error messages for better clarity:
  - "Duplicate username" for existing usernames.
  - "Duplicate email" for emails already in use.
  - "This email is already used in an existing account" for emails found in previousEmails array.
  - 
image

### CODE REVIEW

**Comment by shrprabh** [comment]
The UI Doesn't require any changes since its showing the messages based on the response.

**Comment by dsclassen** [comment]
Here is a scenario:

User's original email is `bob@example.com`
The user changes email to `robert@school.edu`

Forgetting that they changed the email for the account,  at some point they try to get a MagickLink and they use `bob@example.com`. This will give them an error:

```
no account with that email
```

So now they are a bit confused, and they go to the new user registration screen, and try to create an account using `bob@example.com`. Now they get this message:

```
This email is already used in an existing account
```

now what do they do?

**Comment by shrprabh** [comment]
I found a solution to the problem. After the user changes their email address, once the OTP is verified during the final step, we send a confirmation message to the **old email** informing them:

> "Your account email has been updated from **${oldEmail}** to **${newEmail}**. If this was not you, please contact support."

In the scenario where the user tries to log in with the previous email, we can inform them:

> "It looks like you have changed your email. Please try logging in with your updated email address or check your inbox for the updated email."

Alternatively, we can provide the new email associated with their account directly in the error message when they attempt to log in with the old email. For example:

> "Your account is currently associated with **robert@school.edu**. Please use this email to log in."

**Comment by dsclassen** [comment]
I like your idea of sending an email to the old address.
Both of the options for notifying a user if they try to login with a "previous" email seem logical. Maybe let's try the version where we **don't** expose the new email address in the message. What do you think?

**Comment by shrprabh** [comment]
Can we merge this and test this in realtime? I verified in my local using container logs it's working as expected. after that I will add a unit test case for MagicLink.test.ts file.

**Review by dsclassen — APPROVED** [review]
ok

**Pull request merged**
